-- MazePaint online presence setup
-- Run this once in Supabase SQL Editor.
-- Uses the UUID player_id generated by the Windows/Linux client.

create table if not exists public.player_presence (
    player_id uuid primary key,
    username text not null default 'Player',
    is_online boolean not null default false,
    last_seen timestamptz not null default now()
);

create index if not exists player_presence_online_idx
    on public.player_presence (is_online, last_seen desc);

alter table public.player_presence enable row level security;

-- Current MazePaint architecture does not use Supabase Auth yet.
-- These policies are intentionally public to match the publishable-key
-- desktop client. Before public release, add Supabase Auth and tighten RLS.
drop policy if exists "MazePaint presence read" on public.player_presence;
drop policy if exists "MazePaint presence insert" on public.player_presence;
drop policy if exists "MazePaint presence update" on public.player_presence;

create policy "MazePaint presence read"
on public.player_presence
for select
to anon, authenticated
using (true);

create policy "MazePaint presence insert"
on public.player_presence
for insert
to anon, authenticated
with check (true);

create policy "MazePaint presence update"
on public.player_presence
for update
to anon, authenticated
using (true)
with check (true);

-- Chat table is expected to already exist in the project.
-- If it exists, enable Realtime for future websocket integration.
-- Uncomment only if your table has the exact name below and you want
-- Supabase Realtime database changes enabled:
-- alter publication supabase_realtime add table public.chat_messages;
